import { useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'te' | 'hi';

export const languageState = {
  code: 'en' as LanguageCode,
  name: 'English',
};

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    settings: 'Settings',
    account: 'ACCOUNT',
    editProfile: 'Edit profile',
    phoneEmailPassword: 'Phone, email, password',
    myResume: 'My resume',
    verification: 'VERIFICATION',
    verificationStatus: 'Verification status',
    trustScore: 'Trust score',
    inProgress: 'In progress',
    verifiedTier: 'Verified tier',
    notifications: 'NOTIFICATIONS',
    pushNotifications: 'Push notifications',
    jobAlerts: 'Job alerts',
    appUpdates: 'Application updates',
    app: 'APP',
    language: 'Language',
    languageName: 'English',
    theme: 'Theme',
    themeValue: 'white theme default',
    referAFriend: 'Refer a Friend',
    legalSupport: 'LEGAL & SUPPORT',
    termsOfService: 'Terms of service',
    privacyPolicy: 'Privacy policy',
    helpSupport: 'Help & support',
    accountDeletion: 'ACCOUNT DELETION',
    deleteAccount: 'Delete account',
    deactivateAccount: 'Deactivate account',
    permanent: 'Permanent',
    pauseOnly: 'Pause only',
    logOut: 'Log out',
    selectLanguage: 'Select Language',
    allJobs: 'All jobs',
    saved: 'Saved',
    applied: 'Applied',
    profile: 'Profile',
    searchPlaceholder: 'Search by job title, company, or location',
    applyNow: 'Apply Now',
    quickApply: 'Quick Apply',
    uploadPhoto: 'Upload photo',
    publicInfo: 'PUBLIC INFO',
    name: 'Name',
    username: 'Username',
    bio: 'Bio',
    nativeCity: 'Native city',
    gender: 'Gender',
    locationPreferences: 'Location preferences',
    professionalDetails: 'PROFESSIONAL DETAILS',
    education: 'Education',
    skills: 'Skills',
    resume: 'Resume',
    save: 'Save',
    cancel: 'CANCEL',
    continue: 'CONTINUE',
    confirm: 'Confirm',
    verificationCodeSent: 'Verification code sent',
    checkEmailCode: 'Check your registered email for a 6-digit code.',
    enterCodeToDelete: 'Enter the verification code we sent to your registered email to permanently delete your account.',
    enterCodeToDeactivate: 'Enter the verification code we sent to your registered email to pause your account. This is not account deletion.',
  },
  te: {
    settings: 'సెట్టింగ్‌లు',
    account: 'ఖాతా',
    editProfile: 'ప్రొఫైల్‌ను సవరించండి',
    phoneEmailPassword: 'ఫోన్, ఇమెయిల్, పాస్‌వర్డ్',
    myResume: 'నా రెజ్యూమ్',
    verification: 'ధృవీకరణ',
    verificationStatus: 'ధృవీకరణ స్థితి',
    trustScore: 'ట్రస్ట్ స్కోర్',
    inProgress: 'పురోగతిలో ఉంది',
    verifiedTier: 'ధృవీకరించబడిన శ్రేణి',
    notifications: 'నోటిఫికేషన్‌లు',
    pushNotifications: 'పుష్ నోటిఫికేషన్‌లు',
    jobAlerts: 'జాబ్ అలర్ట్‌లు',
    appUpdates: 'అప్లికేషన్ అప్‌డేట్‌లు',
    app: 'యాప్',
    language: 'భాష',
    languageName: 'తెలుగు',
    theme: 'థీమ్',
    themeValue: 'తెలుపు థీమ్ డిఫాల్ట్',
    referAFriend: 'మిత్రుడికి సూచించండి',
    legalSupport: 'చట్టపరమైన మరియు మద్దతు',
    termsOfService: 'సేవా నిబంధనలు',
    privacyPolicy: 'గోప్యతా విధానం',
    helpSupport: 'సహాయం & మద్దతు',
    accountDeletion: 'ఖాతా తొలగింపు',
    deleteAccount: 'ఖాతాను తొలగించండి',
    deactivateAccount: 'ఖాతాను నిలిపివేయండి',
    permanent: 'శాశ్వతం',
    pauseOnly: 'పాజ్ మాత్రమే',
    logOut: 'లాగ్ అవుట్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    allJobs: 'అన్ని ఉద్యోగాలు',
    saved: 'సేవ్ చేసినవి',
    applied: 'దరఖాస్తు చేసినవి',
    profile: 'ప్రొఫైల్',
    searchPlaceholder: 'ఉద్యోగ శీర్షిక, కంపెనీ లేదా స్థానం ద్వారా శోధించండి',
    applyNow: 'ఇప్పుడే దరఖాస్తు చేయండి',
    quickApply: 'త్వరిత దరఖాస్తు',
    uploadPhoto: 'ఫోటోను అప్‌లోడ్ చేయండి',
    publicInfo: 'పబ్లిక్ సమాచారం',
    name: 'పేరు',
    username: 'వినియోగదారు పేరు',
    bio: 'బయో',
    nativeCity: 'సొంత నగరం',
    gender: 'లింగం',
    locationPreferences: 'స్థాన ప్రాధాన్యతలు',
    professionalDetails: 'వృత్తిపరమైన వివరాలు',
    education: 'విద్యార్హత',
    skills: 'నైపుణ్యాలు',
    resume: 'రెజ్యూమ్',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయి',
    continue: 'కొనసాగించు',
    confirm: 'నిర్ధారించు',
    verificationCodeSent: 'ధృవీకరణ కోడ్ పంపబడింది',
    checkEmailCode: '6-అంకెల కోడ్ కోసం మీ రిజిస్టర్డ్ ఇమెయిల్‌ను తనిఖీ చేయండి.',
    enterCodeToDelete: 'మీ ఖాతాను శాశ్వతంగా తొలగించడానికి మీ రిజిస్టర్డ్ ఇమెయిల్‌కు పంపిన ధృవీకరణ కోడ్‌ను నమోదు చేయండి.',
    enterCodeToDeactivate: 'మీ ఖాతాను నిలిపివేయడానికి మీ రిజిస్టర్డ్ ఇమెయిల్‌కు పంపిన ధృవీకరణ కోడ్‌ను నమోదు చేయండి. ఇది ఖాతా తొలగింపు కాదు.',
  },
  hi: {
    settings: 'सेटिंग्स',
    account: 'खाता',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    phoneEmailPassword: 'फोन, ईमेल, पासवर्ड',
    myResume: 'मेरा रेज़्यूमे',
    verification: 'सत्यापन',
    verificationStatus: 'सत्यापन स्थिति',
    trustScore: 'ट्रस्ट स्कोर',
    inProgress: 'प्रगति पर है',
    verifiedTier: 'सत्यापित स्तर',
    notifications: 'सूचनाएं',
    pushNotifications: 'पुश सूचनाएं',
    jobAlerts: 'जॉब अलर्ट',
    appUpdates: 'आवेदन अपडेट',
    app: 'ऐप',
    language: 'भाषा',
    languageName: 'हिन्दी',
    theme: 'थीम',
    themeValue: 'सफेद थीम डिफ़ॉल्ट',
    referAFriend: 'मित्र को संदर्भित करें',
    legalSupport: 'कानूनी और सहायता',
    termsOfService: 'सेवा की शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
    helpSupport: 'सहायता और सहायता',
    accountDeletion: 'खाता हटाना',
    deleteAccount: 'खाता हटाएं',
    deactivateAccount: 'खाता निष्‍क्रिय करें',
    permanent: 'स्थायी',
    pauseOnly: 'केवल रोकें',
    logOut: 'लॉग आउट',
    selectLanguage: 'भाषा चुनें',
    allJobs: 'सभी नौकरियां',
    saved: 'सहेजा गया',
    applied: 'लागू किया गया',
    profile: 'प्रोफ़ाइल',
    searchPlaceholder: 'नौकरी के शीर्षक, कंपनी या स्थान के अनुसार खोजें',
    applyNow: 'अभी आवेदन करें',
    quickApply: 'त्वरित आवेदन',
    uploadPhoto: 'फ़ोटो अपलोड करें',
    publicInfo: 'सार्वजनिक जानकारी',
    name: 'नाम',
    username: 'उपयोगकर्ता नाम',
    bio: 'बायो',
    nativeCity: 'मूल शहर',
    gender: 'लिंग',
    locationPreferences: 'स्थान प्राथमिकताएं',
    professionalDetails: 'पेशेवर विवरण',
    education: 'शिक्षा',
    skills: 'कौशल',
    resume: 'रेज़्यूमे',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    continue: 'जारी रखें',
    confirm: 'पुष्टि करें',
    verificationCodeSent: 'सत्यापन कोड भेजा गया',
    checkEmailCode: '6-अंकीय कोड के लिए अपना पंजीकृत ईमेल जांचें।',
    enterCodeToDelete: 'अपना खाता स्थायी रूप से हटाने के लिए अपने पंजीकृत ईमेल पर भेजा गया सत्यापन कोड दर्ज करें।',
    enterCodeToDeactivate: 'अपना खाता रोकने के लिए अपने पंजीकृत ईमेल पर भेजा गया सत्यापन कोड दर्ज करें। यह खाता हटाना नहीं है।',
  },
};

const langListeners = new Set<() => void>();

export function useLanguage() {
  const [lang, setLang] = useState<LanguageCode>(languageState.code);

  useEffect(() => {
    const listener = () => setLang(languageState.code);
    langListeners.add(listener);
    return () => {
      langListeners.delete(listener);
    };
  }, []);

  const t = (key: string) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return { lang, setLanguage: changeLanguage, t, langName: languageState.name };
}

export function changeLanguage(code: LanguageCode) {
  languageState.code = code;
  languageState.name = code === 'en' ? 'English' : code === 'te' ? 'తెలుగు' : 'हिन्दी';
  langListeners.forEach((fn) => fn());
}
