import type { ReactNode } from 'react';

import * as auth from './screens/seekerAuth';
import * as verify from './screens/seekerVerify';
import * as app from './screens/seekerApp';
import * as onboard from './screens/employerOnboarding';
import * as hr from './screens/employerApp';

export type ScreenDef = {
  id: string;
  title: string;
  source: string;
  caption: string;
  group: string;
  render: () => ReactNode;
};

export const jobseekerScreens: ScreenDef[] = [
  {
    id: 'js-login',
    title: 'Log in',
    source: 'app/index.tsx',
    caption: 'Email and password, Apple and Google, guest browsing, and both signup paths.',
    group: 'Entry',
    render: () => <auth.Login />,
  },
  {
    id: 'js-forgot',
    title: 'Forgot password',
    source: 'app/forgot-password.tsx',
    caption: 'Sends a six digit reset code to the registered email.',
    group: 'Entry',
    render: () => <auth.Forgot />,
  },
  {
    id: 'js-reactivate',
    title: 'Reactivate account',
    source: 'app/reactivate-account.tsx',
    caption: 'Shown when a deactivated account tries to log in, with the deletion date.',
    group: 'Entry',
    render: () => <auth.Reactivate />,
  },
  {
    id: 'js-signup-method',
    title: 'Create account',
    source: 'app/jobseeker-signup.tsx · method',
    caption: 'Apple, Google or email. Google is marked as the fastest path.',
    group: 'Sign up',
    render: () => <auth.SignupMethod />,
  },
  {
    id: 'js-signup-email',
    title: 'Email',
    source: 'app/jobseeker-signup.tsx · email',
    caption: 'Collects the email the verification code is sent to.',
    group: 'Sign up',
    render: () => <auth.SignupEmail />,
  },
  {
    id: 'js-signup-otp',
    title: 'Code',
    source: 'app/jobseeker-signup.tsx · otp',
    caption: 'Six digit code with a resend timer.',
    group: 'Sign up',
    render: () => <auth.SignupOtp />,
  },
  {
    id: 'js-signup-password',
    title: 'Password',
    source: 'app/jobseeker-signup.tsx · password',
    caption: 'Password plus the live requirement checklist.',
    group: 'Sign up',
    render: () => <auth.SignupPassword />,
  },
  {
    id: 'js-signup-resume',
    title: 'Resume',
    source: 'app/jobseeker-signup.tsx · resume',
    caption: 'Resume upload and the fields parsed out of it.',
    group: 'Sign up',
    render: () => <auth.SignupResume />,
  },
  {
    id: 'js-signup-details',
    title: 'Details',
    source: 'app/jobseeker-signup.tsx · details',
    caption: 'Name, gender and phone, prefilled from the resume.',
    group: 'Sign up',
    render: () => <auth.SignupDetails />,
  },
  {
    id: 'js-signup-categories',
    title: 'Work categories',
    source: 'app/jobseeker-signup.tsx · categories',
    caption: 'Work categories that seed the job feed.',
    group: 'Sign up',
    render: () => <auth.SignupCategories />,
  },
  {
    id: 'js-verify-hub',
    title: 'Verification hub',
    source: 'app/verification/hub.tsx',
    caption: 'The six verification steps with progress and a skip.',
    group: 'Verification',
    render: () => <verify.VerifyHub />,
  },
  {
    id: 'js-verify-dashboard',
    title: 'Verification dashboard',
    source: 'app/verification/dashboard.tsx',
    caption: 'Trust score so far and which steps remain.',
    group: 'Verification',
    render: () => <verify.VerifyDashboard />,
  },
  {
    id: 'js-verify-basic',
    title: 'Basic details',
    source: 'app/verification/basic-details.tsx',
    caption: 'Name, city and date of birth, matched to the ID.',
    group: 'Verification',
    render: () => <verify.VerifyBasic />,
  },
  {
    id: 'js-verify-education',
    title: 'Education',
    source: 'app/verification/education.tsx',
    caption: 'Highest qualification from the fixed level list.',
    group: 'Verification',
    render: () => <verify.VerifyEducation />,
  },
  {
    id: 'js-verify-education-status',
    title: 'Education status',
    source: 'app/verification/education-status.tsx',
    caption: 'Completed or pursuing, which decides the document asked for.',
    group: 'Verification',
    render: () => <verify.VerifyEducationStatus />,
  },
  {
    id: 'js-verify-resume',
    title: 'Resume',
    source: 'app/verification/resume.tsx',
    caption: 'The resume already on the profile, with replace and build options.',
    group: 'Verification',
    render: () => <verify.VerifyResume />,
  },
  {
    id: 'js-verify-skills',
    title: 'Skills profile',
    source: 'app/verification/skills.tsx',
    caption: 'Three or more skills adds five points.',
    group: 'Verification',
    render: () => <verify.VerifySkills />,
  },
  {
    id: 'js-verify-documents',
    title: 'Documents',
    source: 'app/verification/documents.tsx',
    caption: 'Optional identity and education documents, including DigiLocker.',
    group: 'Verification',
    render: () => <verify.VerifyDocuments />,
  },
  {
    id: 'js-digilocker',
    title: 'DigiLocker',
    source: 'app/verification/digilocker/flow.tsx',
    caption: 'Prototype DigiLocker connect, consent, select, and fetch flow.',
    group: 'Verification',
    render: () => <verify.SeekerDigilocker />,
  },
  {
    id: 'js-verify-review',
    title: 'Final review',
    source: 'app/verification/review.tsx',
    caption: 'Everything collected, ready to submit for scoring.',
    group: 'Verification',
    render: () => <verify.VerifyReview />,
  },
  {
    id: 'js-trust-score',
    title: 'Trust score',
    source: 'app/verification/trust-score.tsx',
    caption: 'The score and the points that produced it.',
    group: 'Verification',
    render: () => <verify.TrustScore />,
  },
  {
    id: 'js-milestone',
    title: 'Milestone',
    source: 'app/verification/milestone.tsx',
    caption: 'Crossing 70 activates the verified badge.',
    group: 'Verification',
    render: () => <verify.Milestone />,
  },
  {
    id: 'js-all-set',
    title: 'All set',
    source: 'app/verification/all-set.tsx',
    caption: 'Verification finished, straight into the job feed.',
    group: 'Verification',
    render: () => <verify.AllSet />,
  },
  {
    id: 'js-guest-jobs',
    title: 'Guest jobs',
    source: 'app/jobseeker/(tabs)/index.tsx',
    caption: 'A guest can browse. Applied, Saved and Profile route to log in.',
    group: 'Jobs',
    render: () => <app.GuestJobs />,
  },
  {
    id: 'js-jobs',
    title: 'All jobs',
    source: 'app/jobseeker/(tabs)/index.tsx',
    caption: 'Search, category chips, match banner and the job list.',
    group: 'Jobs',
    render: () => <app.Jobs />,
  },
  {
    id: 'js-job',
    title: 'Job',
    source: 'app/jobseeker/job/[id].tsx',
    caption: 'The full listing with save and quick apply.',
    group: 'Jobs',
    render: () => <app.JobDetails />,
  },
  {
    id: 'js-apply',
    title: 'Quick apply',
    source: 'features/jobseeker/components/QuickApplyModal.tsx',
    caption: 'Multi-step Quick Apply: contact, resume, review, and success.',
    group: 'Jobs',
    render: () => <app.QuickApply />,
  },
  {
    id: 'js-apply-now',
    title: 'Apply now',
    source: 'features/jobseeker/components/ApplyNowModal.tsx',
    caption: 'External application flow with trust score and profile attached.',
    group: 'Jobs',
    render: () => <app.ApplyNow />,
  },
  {
    id: 'js-applied',
    title: 'Applied',
    source: 'app/jobseeker/(tabs)/applied.tsx',
    caption: 'Every application with its stage progress.',
    group: 'Jobs',
    render: () => <app.Applied />,
  },
  {
    id: 'js-saved',
    title: 'Saved',
    source: 'app/jobseeker/(tabs)/saved.tsx',
    caption: 'Bookmarked roles, same card as the feed.',
    group: 'Jobs',
    render: () => <app.Saved />,
  },
  {
    id: 'js-profile',
    title: 'Profile',
    source: 'app/jobseeker/(tabs)/profile/index.tsx',
    caption: 'Photo, trust score, verified banner and the profile menu.',
    group: 'Profile',
    render: () => <app.Profile />,
  },
  {
    id: 'js-edit',
    title: 'Edit profile',
    source: 'app/jobseeker/(tabs)/profile/edit.tsx',
    caption: 'Name, headline, about, city and phone.',
    group: 'Profile',
    render: () => <app.EditProfile />,
  },
  {
    id: 'js-profile-education',
    title: 'Resume and education',
    source: 'app/jobseeker/(tabs)/profile/education.tsx',
    caption: 'Qualifications with their verification state.',
    group: 'Profile',
    render: () => <app.ProfileEducation />,
  },
  {
    id: 'js-profile-skills',
    title: 'Skills',
    source: 'app/jobseeker/(tabs)/profile/skills.tsx',
    caption: 'Skills used for the match percentage.',
    group: 'Profile',
    render: () => <app.ProfileSkills />,
  },
  {
    id: 'js-preferences',
    title: 'Job preferences',
    source: 'app/jobseeker/(tabs)/profile/job-preferences.tsx',
    caption: 'Categories, employment type, experience and city.',
    group: 'Profile',
    render: () => <app.Preferences />,
  },
  {
    id: 'js-profile-resume',
    title: 'My resume',
    source: 'app/jobseeker/(tabs)/profile/resume.tsx',
    caption: 'The resume file plus what was parsed from it.',
    group: 'Profile',
    render: () => <app.ProfileResume />,
  },
  {
    id: 'js-account',
    title: 'Account',
    source: 'app/jobseeker/(tabs)/profile/account.tsx',
    caption: 'Email, phone, password and deactivation.',
    group: 'Profile',
    render: () => <app.Account />,
  },
  {
    id: 'js-help',
    title: 'Help',
    source: 'app/jobseeker/(tabs)/profile/help.tsx',
    caption: 'FAQs, support contact and policies.',
    group: 'Profile',
    render: () => <app.Help />,
  },
  {
    id: 'js-settings',
    title: 'Settings',
    source: 'app/jobseeker/(tabs)/profile/settings.tsx',
    caption: 'Account, verification, notifications, appearance, legal, logout.',
    group: 'Settings',
    render: () => <app.SeekerSettings />,
  },
  {
    id: 'js-appearance',
    title: 'Appearance',
    source: 'app/jobseeker/settings/appearance.tsx',
    caption: 'Theme, live preview and language.',
    group: 'Settings',
    render: () => <app.SeekerAppearance />,
  },
  {
    id: 'js-refer',
    title: 'Refer a Friend',
    source: 'app/jobseeker/settings/refer.tsx',
    caption: 'Generate a personal invite link and copy it to share.',
    group: 'Settings',
    render: () => <app.SeekerRefer />,
  },
  {
    id: 'js-language',
    title: 'Language',
    source: 'app/jobseeker/settings/language.tsx',
    caption: 'Select English, Telugu or Hindi. Switches the entire app UI to the chosen language.',
    group: 'Settings',
    render: () => <app.SeekerLanguage />,
  },
  {
    id: 'js-notifications',
    title: 'Notifications',
    source: 'app/jobseeker/settings/notifications.tsx',
    caption: 'Push and email switches plus recent alerts.',
    group: 'Settings',
    render: () => <app.SeekerNotifications />,
  },
];

export const employerScreens: ScreenDef[] = [
  {
    id: 'hr-account',
    title: 'Create workspace',
    source: 'app/create-workspace.tsx · account',
    caption: 'Name, work email and password. Personal domains are blocked.',
    group: 'Workspace',
    render: () => <onboard.HrAccount />,
  },
  {
    id: 'hr-otp',
    title: 'Verify work email',
    source: 'app/signup.tsx · otp',
    caption: 'Six digit code sent to the work address.',
    group: 'Workspace',
    render: () => <onboard.HrOtp />,
  },
  {
    id: 'hr-verify-intro',
    title: 'Why verify',
    source: 'app/create-workspace.tsx · verify_intro',
    caption: 'Trust, reach and candidate messaging, or skip and post unverified.',
    group: 'Workspace',
    render: () => <onboard.HrVerifyIntro />,
  },
  {
    id: 'hr-whos-hiring',
    title: "Who's hiring",
    source: 'app/create-workspace.tsx · whos_hiring',
    caption: 'Registered company, small business, or an individual.',
    group: 'Workspace',
    render: () => <onboard.HrWhosHiring />,
  },
  {
    id: 'hr-verify-company',
    title: 'Verify company',
    source: 'app/create-workspace.tsx · verify_company',
    caption: 'GSTIN, CIN and company PAN checked against the official registries.',
    group: 'Workspace',
    render: () => <onboard.HrVerifyCompany />,
  },
  {
    id: 'hr-verify-small',
    title: 'Verify small business',
    source: 'app/create-workspace.tsx · verify_small',
    caption: 'Udyam number or uploaded business proof.',
    group: 'Workspace',
    render: () => <onboard.HrVerifySmall />,
  },
  {
    id: 'hr-verify-individual',
    title: 'Verify identity',
    source: 'app/create-workspace.tsx · verify_individual',
    caption: 'DigiLocker or a manual PAN and Aadhaar upload.',
    group: 'Workspace',
    render: () => <onboard.HrVerifyIndividual />,
  },
  {
    id: 'hr-digilocker-auth',
    title: 'DigiLocker consent',
    source: 'app/create-workspace.tsx · digilocker_auth',
    caption: 'The documents Applywizard asks DigiLocker for.',
    group: 'Workspace',
    render: () => <onboard.HrDigilockerAuth />,
  },
  {
    id: 'hr-digilocker-loading',
    title: 'DigiLocker fetch',
    source: 'app/create-workspace.tsx · digilocker_loading',
    caption: 'Waiting on DigiLocker, usually 15 to 30 seconds.',
    group: 'Workspace',
    render: () => <onboard.HrDigilockerLoading />,
  },
  {
    id: 'hr-individual-success',
    title: 'Identity submitted',
    source: 'app/create-workspace.tsx · verify_individual_success',
    caption: 'Aadhaar and PAN queued for the ops team.',
    group: 'Workspace',
    render: () => <onboard.HrIndividualSuccess />,
  },
  {
    id: 'hr-verified',
    title: 'Submitted for review',
    source: 'app/create-workspace.tsx · verified',
    caption: 'What was submitted and what the badge unlocks.',
    group: 'Workspace',
    render: () => <onboard.HrVerified />,
  },
  {
    id: 'hr-post-1',
    title: 'Post a job · role',
    source: 'app/create-workspace.tsx · post_job_1',
    caption: 'Title, department, employment type and experience.',
    group: 'Post a job',
    render: () => <onboard.HrPost1 />,
  },
  {
    id: 'hr-post-2',
    title: 'Post a job · details',
    source: 'app/create-workspace.tsx · post_job_2',
    caption: 'Description, requirements and skills. Vague listings get flagged.',
    group: 'Post a job',
    render: () => <onboard.HrPost2 />,
  },
  {
    id: 'hr-post-3',
    title: 'Post a job · pay',
    source: 'app/create-workspace.tsx · post_job_3',
    caption: 'Salary against the market band, location, mode and deadline.',
    group: 'Post a job',
    render: () => <onboard.HrPost3 />,
  },
  {
    id: 'hr-post-4',
    title: 'Post a job · hiring setup',
    source: 'app/create-workspace.tsx · post_job_4',
    caption: 'Hiring manager, pipeline stages and screening questions.',
    group: 'Post a job',
    render: () => <onboard.HrPost4 />,
  },
  {
    id: 'hr-home',
    title: 'Home',
    source: 'app/hr-screens/index.tsx · OverviewTab',
    caption: 'Snapshot cards, hiring funnel, alerts and today’s interviews.',
    group: 'Workspace tabs',
    render: () => <hr.HrHome />,
  },
  {
    id: 'hr-jobs',
    title: 'Jobs',
    source: 'components/hr-screens/JobsTab.tsx',
    caption: 'Every open role with its applied, shortlist, interview and offer counts.',
    group: 'Workspace tabs',
    render: () => <hr.HrJobs />,
  },
  {
    id: 'hr-candidates',
    title: 'Candidates',
    source: 'components/hr-screens/CandidatesTab.tsx',
    caption: 'Everyone who applied, filtered by stage.',
    group: 'Workspace tabs',
    render: () => <hr.HrCandidates />,
  },
  {
    id: 'hr-interviews',
    title: 'Interviews',
    source: 'components/hr-screens/InterviewsTab.tsx',
    caption: 'Scheduled calls and who has not confirmed.',
    group: 'Workspace tabs',
    render: () => <hr.HrInterviews />,
  },
  {
    id: 'hr-more',
    title: 'More',
    source: 'components/hr-screens/HrMoreTab.tsx',
    caption: 'Post a job, company profile, active jobs, all candidates, settings, logout.',
    group: 'Workspace tabs',
    render: () => <hr.HrMore />,
  },
  {
    id: 'hr-job',
    title: 'Job',
    source: 'app/hr-screens/job/[id].tsx',
    caption: 'One listing, its counts and its applicants.',
    group: 'Hiring',
    render: () => <hr.HrJob />,
  },
  {
    id: 'hr-job-details',
    title: 'Job details',
    source: 'app/hr-screens/job-details/[id].tsx',
    caption: 'Edit the listing, pause it or close it.',
    group: 'Hiring',
    render: () => <hr.HrJobDetails />,
  },
  {
    id: 'hr-candidate',
    title: 'Candidate',
    source: 'app/hr-screens/candidate/[id].tsx',
    caption: 'Verified profile, match reasons, screening answers and stage control.',
    group: 'Hiring',
    render: () => <hr.HrCandidate />,
  },
  {
    id: 'hr-company',
    title: 'Company profile',
    source: 'app/hr-screens/company.tsx',
    caption: 'What candidates see about the company.',
    group: 'Hiring',
    render: () => <hr.HrCompany />,
  },
  {
    id: 'hr-pipeline',
    title: 'Pipeline',
    source: 'components/hr-screens/PipelineTab.tsx',
    caption: 'Applicants grouped by stage for one job.',
    group: 'Hiring',
    render: () => <hr.HrPipeline />,
  },
  {
    id: 'hr-analytics',
    title: 'Analytics',
    source: 'app/hr-screens/analytics.tsx',
    caption: 'Open jobs, applicants, average match and sources.',
    group: 'Hiring',
    render: () => <hr.HrAnalytics />,
  },
  {
    id: 'hr-desktop',
    title: 'Open on desktop',
    source: 'app/hr-screens/desktop.tsx',
    caption: 'Bulk actions and exports live on the desktop workspace.',
    group: 'Hiring',
    render: () => <hr.HrDesktop />,
  },
  {
    id: 'hr-settings',
    title: 'Settings',
    source: 'app/hr-screens/settings/index.tsx',
    caption: 'Profile, company, notifications, security, appearance, help, refer.',
    group: 'Settings',
    render: () => <hr.HrSettings />,
  },
  {
    id: 'hr-my-profile',
    title: 'My Profile',
    source: 'app/hr-screens/settings/my-profile.tsx',
    caption: 'The recruiter’s own details and photo.',
    group: 'Settings',
    render: () => <hr.HrMyProfile />,
  },
  {
    id: 'hr-settings-company',
    title: 'Company',
    source: 'app/hr-screens/settings/company.tsx',
    caption: 'Company details and branding, with verification state.',
    group: 'Settings',
    render: () => <hr.HrSettingsCompany />,
  },
  {
    id: 'hr-settings-notifications',
    title: 'Notifications',
    source: 'app/hr-screens/settings/notifications.tsx',
    caption: 'Email and push for applications and interviews.',
    group: 'Settings',
    render: () => <hr.HrSettingsNotifications />,
  },
  {
    id: 'hr-security',
    title: 'Privacy & Security',
    source: 'app/hr-screens/settings/security.tsx',
    caption: 'Password, active sessions and data retention.',
    group: 'Settings',
    render: () => <hr.HrSecurity />,
  },
  {
    id: 'hr-appearance',
    title: 'Appearance',
    source: 'app/hr-screens/settings/appearance.tsx',
    caption: 'Theme, preview and language for the hiring app.',
    group: 'Settings',
    render: () => <hr.HrAppearance />,
  },
  {
    id: 'hr-help',
    title: 'Help & support',
    source: 'app/hr-screens/settings/help.tsx',
    caption: 'FAQs, support contacts and policies.',
    group: 'Settings',
    render: () => <hr.HrHelp />,
  },
  {
    id: 'hr-refer',
    title: 'Refer a recruiter',
    source: 'app/hr-screens/settings/index.tsx · refer',
    caption: 'Invite another recruiter with a referral code.',
    group: 'Settings',
    render: () => <hr.HrRefer />,
  },
];

export function indexScreens(screens: ScreenDef[]) {
  return new Map(screens.map((screen) => [screen.id, screen]));
}
